### ISSUE TITLE
[Major] Filter level of commitment not working 

### ISSUE THREAD

**Issue by ifrahm** [info442-sp21/d-team#69] opened 2021-05-25 21:10 UTC
**Describe the bug**
When the low checkbox is selected the medium and high commitment level cards are still there, there is no change.

 Mac Os Big Sur, Chrome

**To Reproduce**
1. Sign In 
2. Click Home 
3. Select checkboxes on top of screen

**Actual behavior**
All the cards remain and when filter checkboxes are selected, the cards displayed are not updated

**Expected behavior**
Expected cards that are only of low commitment level to me displayed when the "low "checkbox is selected

**Comment by ashshah1** [comment] 2021-05-27 21:03
This will be fixed in the next development sprint.

**Comment by kristina-te** [comment] 2021-05-27 21:18
Invalid because it was not a bug, it was just not implemented.

**Comment by cherimarie** [comment] 2021-06-02 02:30
I agree with the reporter that this is a major bug. The filters are presented to users as a feature that can be used, they should either work or not be shown.

**Comment by ashshah1** [comment] 2021-06-05 22:37
This issue has been fixed, users can now filter their newsfeed content based off of commitment levels: https://github.com/info442-sp21/d-team/commit/db7dda61bc65dcc5eb714f9f7b02af8807348785

**Closed by ashshah1** 2021-06-05 22:37 UTC
Labels: bug
