### ISSUE TITLE
[Minor] Deleting an account reroutes to blank page

### ISSUE THREAD

**Issue by yejukim** [info442-sp21/d-team#85] opened 2021-05-25 21:46 UTC
**Describe the bug**
When I clicked delete account, nothing happened. When I tried to navigate to another page, the whole page went white. 

**To Reproduce**
1. Go to 'My Profile'
2. Click on 'Delete Account'
3. Click on Home page
4. See white page

**Expected behavior**
Home page with sign in button
**Screenshots**
![Screen Shot 2021-05-25 at 2 44 35 PM](https://user-images.githubusercontent.com/55808078/119572637-e9662a00-bd67-11eb-8ea9-6fecc1e1e8f6.png)

Environment: Chrome 90.0.4430.93 on macOS (Mojave)

**Comment by ashshah1** [comment] 2021-05-27 22:12
We agree that this is a bug, we were unable to reproduce it more than one (as the delete account button does usually redirect to home upon deletion) so this is a rare issue. Given our time frame, we may not be able to address this and are therefore marking it as a "won't fix" but will attempt to pursue this if we have time.

**Comment by ashshah1** [comment] 2021-05-30 18:41
Bug has been fixed: https://github.com/info442-sp21/d-team/commit/37fd2dd6fd2e133695b55762176b544abfa5f70a

**Closed by ashshah1** 2021-05-30 18:41 UTC
Labels: bug
